#!/usr/bin/env bash
#
# bootstrap install things

if test ! $(which brew)
then
  echo " Install Homebrew..."
  if test "$(uname)" = "Darwin"
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
else
  echo " Homebrew has been installed"
fi
