require'plugins'
require'configs'



-- -- Install packer
-- local install_path = vim.fn.stdpath 'data' .. '/site/pack/packer/start/packer.nvim'
-- local is_bootstrap = false
-- if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
--   is_bootstrap = true
--   vim.fn.execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
--   vim.cmd [[packadd packer.nvim]]
-- end
--
-- -- stylua: ignore start
-- require('packer').startup(function(use)
--   use 'wbthomason/packer.nvim'                            -- Package manager
--
--   use {'vim-airline/vim-airline'}
--
--   use {'mileszs/ack.vim'}
--   use {'tpope/vim-fugitive'}
--   use {'junegunn/fzf'}
--   use {'junegunn/fzf.vim'}
--   use {'tpope/vim-surround'}
--   use {'tpope/vim-repeat'}
--   use {'slim-template/vim-slim'}
--   use {'vim-ruby/vim-ruby'}
--   use {'tpope/vim-rails'}
--
--   use {'MarcWeber/vim-addon-mw-utils'}
--   use {'tomtom/tlib_vim'}
--   use {'garbas/vim-snipmate'}
--   use {'honza/vim-snippets'}
--
--   use {'neoclide/coc.nvim', branch = 'release'}
--   use { "nvim-lua/plenary.nvim", module = "plenary" }
--   use 'neovim/nvim-lspconfig' -- Configurations for Nvim LSP
--   use {
--      'nvim-telescope/telescope.nvim', tag = '0.1.0'
--   }
--   -- use {
--   --   "windwp/nvim-autopairs",
--   --   config = function() require("nvim-autopairs").setup {} end
--   -- }
--   use {
--     'numToStr/Comment.nvim',
--   }
--   use {
--     'nvim-tree/nvim-tree.lua'
--   }
--
--   use 'nvim-tree/nvim-web-devicons'
--   -- use {
--   --   "nvim-tree/nvim-web-devicons",
--   --   module = "nvim-web-devicons"
--   -- }
--
--   if is_bootstrap then
--     require('packer').sync()
--   end
-- end)
--
-- if is_bootstrap then
--   print '=================================='
--   print '    Plugins are being installed'
--   print '    Wait until Packer completes,'
--   print '       then restart nvim'
--   print '=================================='
--   return
-- end

